using UnityEditor;
using UnityEngine;
using System.IO;

/// <summary>
/// Version management utility for the project.
/// Updates version from git tags or build info.
/// </summary>
[InitializeOnLoad]
public static class VersionManager
{
    private const string BuildInfoPath = "build-info.json";

    static VersionManager()
    {
        // Auto-update version on editor load if build-info.json exists
        UpdateVersionFromBuildInfo();
    }

    [MenuItem("Build/Update Version from Git")]
    public static void UpdateVersionFromGit()
    {
        try
        {
            // Try to get version from git describe
            string version = ExecuteGitCommand("describe --tags --always --dirty");

            if (!string.IsNullOrEmpty(version))
            {
                // Clean up version string (remove 'v' prefix if present)
                version = version.TrimStart('v');

                PlayerSettings.bundleVersion = version;
                Debug.Log($"Updated version to: {version}");
            }
            else
            {
                Debug.LogWarning("Could not get version from git");
            }
        }
        catch (System.Exception e)
        {
            Debug.LogError($"Failed to update version from git: {e.Message}");
        }
    }

    [MenuItem("Build/Show Current Version")]
    public static void ShowCurrentVersion()
    {
        Debug.Log($"Current version: {PlayerSettings.bundleVersion}");
        Debug.Log($"Product name: {PlayerSettings.productName}");
        Debug.Log($"Company name: {PlayerSettings.companyName}");
    }

    /// <summary>
    /// Update version from build-info.json if it exists.
    /// This file is generated by git-build-info package.
    /// </summary>
    private static void UpdateVersionFromBuildInfo()
    {
        string buildInfoFile = Path.Combine(Application.dataPath, "..", BuildInfoPath);

        if (File.Exists(buildInfoFile))
        {
            try
            {
                string json = File.ReadAllText(buildInfoFile);
                BuildInfo buildInfo = JsonUtility.FromJson<BuildInfo>(json);

                if (!string.IsNullOrEmpty(buildInfo.version))
                {
                    string version = buildInfo.version.TrimStart('v');
                    PlayerSettings.bundleVersion = version;
                    Debug.Log($"Updated version from build-info.json: {version}");
                }
            }
            catch (System.Exception e)
            {
                Debug.LogWarning($"Could not parse build-info.json: {e.Message}");
            }
        }
    }

    /// <summary>
    /// Execute a git command and return the output.
    /// </summary>
    private static string ExecuteGitCommand(string arguments)
    {
        System.Diagnostics.ProcessStartInfo startInfo = new System.Diagnostics.ProcessStartInfo
        {
            FileName = "git",
            Arguments = arguments,
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            CreateNoWindow = true,
            WorkingDirectory = Application.dataPath
        };

        using (System.Diagnostics.Process process = System.Diagnostics.Process.Start(startInfo))
        {
            string output = process.StandardOutput.ReadToEnd().Trim();
            string error = process.StandardError.ReadToEnd().Trim();
            process.WaitForExit();

            if (process.ExitCode != 0)
            {
                Debug.LogWarning($"Git command failed: {error}");
                return null;
            }

            return output;
        }
    }

    [System.Serializable]
    private class BuildInfo
    {
        public string version;
        public string commit;
        public string branch;
        public string buildDate;
    }
}
